import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { defineSecret } from 'firebase-functions/params';
import { logger } from 'firebase-functions';

const groqKey = defineSecret('GROQ_API_KEY');
const geminiKey = defineSecret('GEMINI_API_KEY');

interface GenerateRequest {
  title: string;
  spokenInput: string;
  prompt: string;
  targets: string[];
  deployPath: string;
  customDomain?: string | null;
}

interface GeneratedFile {
  path: string;
  content: string;
}

async function generateViaGroq(systemPrompt: string, userPrompt: string) {
  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${groqKey.value()}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.2,
      response_format: { type: 'json_object' },
    }),
  });

  if (!response.ok) {
    throw new Error(`Groq failed (${response.status})`);
  }

  const data = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  return data.choices?.[0]?.message?.content || '{}';
}

async function generateViaGemini(systemPrompt: string, userPrompt: string) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiKey.value()}`;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }] }],
      generationConfig: {
        temperature: 0.2,
        responseMimeType: 'application/json',
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`Gemini failed (${response.status})`);
  }

  const data = (await response.json()) as {
    candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>;
  };
  return data.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
}

function fallbackFiles(title: string): GeneratedFile[] {
  return [
    {
      path: 'web/index.html',
      content: `<html><body><h1>${title}</h1><p>Generated by Titans-Lab</p></body></html>`,
    },
    {
      path: 'backend/firebase-rules.txt',
      content: 'rules_version = \"2\";\nservice cloud.firestore {\n  match /databases/{database}/documents {\n    match /{document=**} {\n      allow read, write: if request.auth != null;\n    }\n  }\n}',
    },
  ];
}

export const generateAppBlueprint = onCall(
  { secrets: [groqKey, geminiKey] },
  async (request) => {
    if (!request.auth) {
      throw new HttpsError('unauthenticated', 'Login is required.');
    }

    const payload = request.data as GenerateRequest;
    if (!payload?.title || (!payload.prompt && !payload.spokenInput)) {
      throw new HttpsError('invalid-argument', 'Missing required build fields.');
    }

    const systemPrompt = `You are Titans-Lab, an elite AI software architect. Return valid JSON only with shape:
  {"status":"ready","stack":"string","prompt":"string","spokenInput":"string","targets":["..."],"deployPath":"string","customDomain":"string|null","files":[{"path":"string","content":"string"}]}`;
    const userPrompt = `Title: ${payload.title}\nVoice idea: ${payload.spokenInput}\nExtra: ${payload.prompt}\nTargets: ${payload.targets.join(', ')}\nDeployment: ${payload.deployPath}\nCustom domain: ${payload.customDomain ?? 'none'}\nBuild a secure Firebase-backed app with clean starter code and API contracts.`;

    let raw = '{}';
    try {
      raw = await generateViaGroq(systemPrompt, userPrompt);
    } catch (error) {
      logger.warn('Groq unavailable, falling back to Gemini', error);
      raw = await generateViaGemini(systemPrompt, userPrompt);
    }

    try {
      const parsed = JSON.parse(raw) as {
        status?: 'ready' | 'failed';
        stack?: string;
        files?: GeneratedFile[];
      };

      return {
        title: payload.title,
        prompt: payload.prompt,
        spokenInput: payload.spokenInput,
        targets: payload.targets,
        status: parsed.status ?? 'ready',
        stack: parsed.stack ?? 'Firebase + React + Functions',
        deployPath: payload.deployPath,
        customDomain: payload.customDomain ?? undefined,
        files: parsed.files?.length ? parsed.files : fallbackFiles(payload.title),
      };
    } catch (error) {
      logger.error('Model response parse failed', error);
      return {
        title: payload.title,
        prompt: payload.prompt,
        spokenInput: payload.spokenInput,
        targets: payload.targets,
        status: 'ready' as const,
        stack: 'Firebase + React + Functions',
        deployPath: payload.deployPath,
        customDomain: payload.customDomain ?? undefined,
        files: fallbackFiles(payload.title),
      };
    }
  },
);
